# Site
# repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Calvin Yu
title: Software Engineer and Electrical Engineering Doctorate Student
email: calvinkyu91@gmail.com


# Social links
# twitter_username: facespics
github_username:  cyu9
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: cyuu91
linkedin_username: calvinyu91
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/image.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Calvin and I'm a software engineer in the medical devices
  industry. I'm also a electrical engineering doctorate student.


  I am most skilled in: <mark>Software Development</mark> and <mark>Snacking</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in software engineering some of my other interests and hobbies are:
   - Personal Training
   - Drinking Tea
   - Reading


# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
